[pytest]
# 1. Default command line arguments (saves you typing flags every time)
# addopts = -v --tb=short --strict-markers
addopts = --html=reports/report.html --self-contained-html

# 2. Minimum version of pytest required to run the tests
minversion = 9.1

# 3. Directories where pytest should search for tests (improves discovery speed)
testpaths = tests

# 4. Custom test naming patterns (if you don't use standard test_*.py naming)
python_files = test_*.py      # check_*.py  (exclude this for time being)
python_classes = Test* Suite*
python_functions = test_*

# 5. Register custom markers to avoid "unknown marker" warnings
# markers =
#     slow: marks tests as slow (deselect with '-m "not slow"')
#     smoke: core application functionality tests

# 6. Add directories directly to the Python path (useful for finding the 'src' folder)
pythonpath = src

# 7. Configure console output log levels
log_cli = true
log_cli_level = INFO
